---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: bookinfo-reviews
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: reviews
        image: 736059458620.dkr.ecr.us-east-1.amazonaws.com/prod/devops-on-aws-all-in-one:reviews-latest
        imagePullPolicy: Always
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        - name: ENABLE_RATINGS
          value: "true"
        - name: STAR_COLOR
          value: "black"
        - name: DB_TYPE
          value: mongodb
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}

