---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: ratings
        image: 736059458620.dkr.ecr.us-east-1.amazonaws.com/prod/devops-on-aws-all-in-one:ratings-latest
        
        imagePullPolicy: Always
        env:
        - name: SERVICE_VERSION
          value: "v1"

        # - name: SERVICE_VERSION
        #   value: "v2"
        # - name: DB_TYPE
        #   value: "mongodb"
        # - name: MONGO_DB_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: ratings-mongodb-secret
        #       key: MONGO_DB_URL

        # - name: SERVICE_VERSION
        #   value: "v2"
        # - name: DB_TYPE
        #   value: "mysql"
        # - name: MYSQL_DB_HOST
        #   value: "mysqldb"
        # - name: MYSQL_DB_PORT
        #   value: "3306"
        # - name: MYSQL_DB_USER
        #   value: "admin"
        # - name: MYSQL_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: ratings-mysql-password
        #       key: MYSQL_DB_PASSWORD

        ports:
        - containerPort: 9080
