name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: prod/devops-on-aws-all-in-one
  NAMESPACE: default

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deployment: productpage-v1
            image_name: productpage
            container: productpage

          - deployment: details-v1
            image_name: details
            container: details

          - deployment: ratings-v1
            image_name: ratings
            container: ratings

          - deployment: reviews-v1
            image_name: reviews
            container: reviews

          - deployment: reviews-v2
            image_name: reviews
            container: reviews

          - deployment: reviews-v3
            image_name: reviews
            container: reviews

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Set kubeconfig
        run: |
          mkdir -p ~/.kube
          printf '%s' "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update deployment image
        run: |
          kubectl set image deployment/${{ matrix.deployment }} ${{ matrix.container }}=736059458620.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ matrix.image_name }}-${{ github.event.workflow_run.head_sha }} -n ${{ env.NAMESPACE }}

      - name: Check rollout status
        run: |
          kubectl rollout status deployment/${{ matrix.deployment }} \
            -n ${{ env.NAMESPACE }} --timeout=180s